/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sth_s2;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.AffineTransform;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Line2D;
import java.awt.image.AffineTransformOp;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Nezz
 */
public class ApplicationInterface extends javax.swing.JFrame {

    /**
     * Creates new form ApplicationInterface
     */
    private int xStart;
    private int xEnd;
    private int yStart;
    private int yEnd;
    private BufferedImage image;

    private Line2D linebuffer;
    private Ellipse2D circbuffer;
    private Graphics2D g2;
    private Graphics g;

    private List<Line2D> lineContainer = new ArrayList();
    private List<Ellipse2D> circContainer = new ArrayList();
    private List<MyImage> imgContainer = new ArrayList();

    private Circuit cir;

    public ApplicationInterface() {
        initComponents();
    }

    public ApplicationInterface(Circuit cir) {
        initComponents();
        this.cir = cir;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        nouveauLabel = new javax.swing.JLabel();
        condensateurButton = new javax.swing.JButton();
        noeudButton = new javax.swing.JButton();
        genButton = new javax.swing.JButton();
        resistanceButton = new javax.swing.JButton();
        bobineButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        calculsButton = new javax.swing.JButton();
        nouveauButton = new javax.swing.JButton();
        ouvrirButton = new javax.swing.JButton();
        sauvegarderButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        mainPanel = new javax.swing.JPanel();
        jButtonCLEAR = new javax.swing.JButton();
        jRadioButtonLine = new javax.swing.JRadioButton();
        refrechirJButon = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        consoleTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion Circuits RLC");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 10));

        nouveauLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nouveauLabel.setText("Nouveaux :");
        jPanel1.add(nouveauLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 110, 30));

        condensateurButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        condensateurButton.setText("Condensateur");
        condensateurButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                condensateurButtonActionPerformed(evt);
            }
        });
        jPanel1.add(condensateurButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 140, 30));

        noeudButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        noeudButton.setText("Noeud");
        noeudButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noeudButtonActionPerformed(evt);
            }
        });
        jPanel1.add(noeudButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 140, 30));

        genButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        genButton.setText("Gen. Tension");
        genButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genButtonActionPerformed(evt);
            }
        });
        jPanel1.add(genButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 140, 30));

        resistanceButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resistanceButton.setText("Résistance");
        resistanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resistanceButtonActionPerformed(evt);
            }
        });
        jPanel1.add(resistanceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 140, 30));

        bobineButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bobineButton.setText("Bobine");
        bobineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bobineButtonActionPerformed(evt);
            }
        });
        jPanel1.add(bobineButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 140, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 160, 580));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        calculsButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        calculsButton.setText("Calculs...");
        calculsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculsButtonActionPerformed(evt);
            }
        });
        jPanel2.add(calculsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 100, 30));

        nouveauButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nouveauButton.setText("Nouveau");
        nouveauButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nouveauButtonActionPerformed(evt);
            }
        });
        jPanel2.add(nouveauButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 11, 100, 30));

        ouvrirButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ouvrirButton.setText("Ouvrir....");
        jPanel2.add(ouvrirButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 100, 30));

        sauvegarderButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sauvegarderButton.setText("Sauvegarder...");
        jPanel2.add(sauvegarderButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 130, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Console :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 60, 30));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1010, 90));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mainPanelMouseDragged(evt);
            }
        });
        mainPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mainPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mainPanelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 610, -1));

        jButtonCLEAR.setText("Supprimer");
        jButtonCLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCLEARActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCLEAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, -1, -1));

        jRadioButtonLine.setText("Fil");
        getContentPane().add(jRadioButtonLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, -1, -1));

        refrechirJButon.setText("Actualiser");
        refrechirJButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrechirJButonActionPerformed(evt);
            }
        });
        getContentPane().add(refrechirJButon, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, -1, -1));

        consoleTextArea.setColumns(20);
        consoleTextArea.setRows(5);
        jScrollPane1.setViewportView(consoleTextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 790, 220));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void genButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genButtonActionPerformed
        // TODO add your handling code here:
        ComposantInterface ci = new ComposantInterface("Fem              :", "V", cir, consoleTextArea, mainPanel, lineContainer, circContainer, imgContainer);
        ci.setVisible(true);
    }//GEN-LAST:event_genButtonActionPerformed

    private void resistanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resistanceButtonActionPerformed
        // TODO add your handling code here:
        ComposantInterface ci = new ComposantInterface("Résistance     :", "Ohm", cir, consoleTextArea, mainPanel, lineContainer, circContainer, imgContainer);
        ci.setVisible(true);
    }//GEN-LAST:event_resistanceButtonActionPerformed

    private void bobineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bobineButtonActionPerformed
        // TODO add your handling code here:
        ComposantInterface ci = new ComposantInterface("Inductance     :", "H", cir, consoleTextArea, mainPanel, lineContainer, circContainer, imgContainer);
        ci.setVisible(true);
    }//GEN-LAST:event_bobineButtonActionPerformed

    private void condensateurButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_condensateurButtonActionPerformed
        // TODO add your handling code here:
        ComposantInterface ci = new ComposantInterface("Condensateur   :", "F", cir, consoleTextArea, mainPanel, lineContainer, circContainer, imgContainer);
        ci.setVisible(true);
    }//GEN-LAST:event_condensateurButtonActionPerformed

    private void calculsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculsButtonActionPerformed
        // TODO add your handling code here:
        CalculsInterface cal = null;
        try {
            cal = new CalculsInterface(cir);
        } catch (Exception ex) {
            Logger.getLogger(ApplicationInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
        cal.setVisible(true);
    }//GEN-LAST:event_calculsButtonActionPerformed

    private void noeudButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noeudButtonActionPerformed
        // TODO add your handling code here:
        NoeudInterface ni = new NoeudInterface(cir, consoleTextArea, mainPanel, lineContainer, circContainer, imgContainer);
        ni.setVisible(true);
    }//GEN-LAST:event_noeudButtonActionPerformed

    private void mainPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainPanelMousePressed

        if (g2 == null) {
            g2 = (Graphics2D) mainPanel.getGraphics();
        }
        xStart = evt.getX();
        yStart = evt.getY();
        xEnd = evt.getX();
        yEnd = evt.getY();

    }//GEN-LAST:event_mainPanelMousePressed

    private void mainPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainPanelMouseReleased
        if (jRadioButtonLine.isSelected()) {
            mainPanel.update(g2);
            xEnd = evt.getX();
            yEnd = evt.getY();
            linebuffer = new Line2D.Float((float) xStart, (float) yStart, (float) xEnd, (float) yEnd);
            lineContainer.add(linebuffer);
            DrawAll();
        }

    }//GEN-LAST:event_mainPanelMouseReleased

    private void mainPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainPanelMouseDragged

        if (jRadioButtonLine.isSelected()) {
            mainPanel.update(g2);
            xEnd = evt.getX();
            yEnd = evt.getY();
            linebuffer = new Line2D.Float((float) xStart, (float) yStart, (float) xEnd, (float) yEnd);
            DrawAll();
            g2.draw(linebuffer);
        }
    }//GEN-LAST:event_mainPanelMouseDragged

    private void jButtonCLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCLEARActionPerformed
        if (g2 == null) {
            g2 = (Graphics2D) mainPanel.getGraphics();
        }
        mainPanel.update(g2);
        lineContainer.clear();
        circContainer.clear();
        imgContainer.clear();
        cir = new Circuit();
        consoleTextArea.setText("");
    }//GEN-LAST:event_jButtonCLEARActionPerformed

    private void nouveauButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nouveauButtonActionPerformed
        // TODO add your handling code here:
        if (g2 == null) {
            g2 = (Graphics2D) mainPanel.getGraphics();
        }
        mainPanel.update(g2);
        lineContainer.clear();
        circContainer.clear();
        imgContainer.clear();
        cir = new Circuit();
        consoleTextArea.setText("");
    }//GEN-LAST:event_nouveauButtonActionPerformed

    private void refrechirJButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrechirJButonActionPerformed
        // TODO add your handling code here:
        if (g2 == null) {
            g2 = (Graphics2D) mainPanel.getGraphics();
        }
        DrawAll();
    }//GEN-LAST:event_refrechirJButonActionPerformed

    private void DrawAll() {
        for (int x = 0; x < lineContainer.size(); x++) {
            g2.draw(lineContainer.get(x));
        }
        for (int x = 0; x < circContainer.size(); x++) {
            g2.draw(circContainer.get(x));
        }
        for (int x = 0; x < imgContainer.size(); x++) {
            MyImage img =imgContainer.get(x);
            //Rotation 
            double rotX=img.getImg().getWidth()/2;
            double rotY=img.getImg().getHeight()/2;
            AffineTransform rot=AffineTransform.getRotateInstance(img.getRot(),rotX,rotY);
            AffineTransformOp op =new AffineTransformOp(rot,AffineTransformOp.TYPE_BILINEAR);
            g2.drawImage(op.filter(img.getImg(), null), img.getX(),img.getY() ,null);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicationInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicationInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicationInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Circuit c = new Circuit();
                ApplicationInterface g = new ApplicationInterface(c);
                g.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bobineButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton calculsButton;
    private javax.swing.JButton condensateurButton;
    private javax.swing.JTextArea consoleTextArea;
    private javax.swing.JButton genButton;
    private javax.swing.JButton jButtonCLEAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonLine;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton noeudButton;
    private javax.swing.JButton nouveauButton;
    private javax.swing.JLabel nouveauLabel;
    private javax.swing.JButton ouvrirButton;
    private javax.swing.JButton refrechirJButon;
    private javax.swing.JButton resistanceButton;
    private javax.swing.JButton sauvegarderButton;
    // End of variables declaration//GEN-END:variables
}
