/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sth_s2;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Nezz
 */
public class CalculsInterface extends javax.swing.JFrame {

    private Circuit c;

    /**
     * Creates new form Calculs
     */
    public CalculsInterface(Circuit c) throws Exception {
        initComponents();
        this.c = c;
        circuitJTextPanel.setText(c.toString());
        double pulsation = Double.parseDouble(jTextField1.getText());

        try {
            MatriceRectangulaire mrec = c.calculs(pulsation);
            Complex[] mat = mrec.getSol();
            int n = c.getCompoCircuit().size();
            for (Composant cur : c.getCompoCircuit()) {
                int id = cur.getId() - 1;

                Complex v = mat[id];
                Complex i = mat[id + n];
                String out = cur.toString();
                out += ": V =[ComPol " + v.module() + "ei(" + v.argument() + ")]; I = [ComPol";
                out += i.module() + " ei(" + i.argument() + ")]\n";
                calculTextArea.append(out);/*ajouter text*/
            }
        } catch (Exception e) {
            calculTextArea.setText("Vérifier la validité du Circuit !!!");
        }
    }

    public CalculsInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        circuitJTextPanel = new javax.swing.JTextPane();
        pulsationLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        recalculeButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        calculTextArea = new javax.swing.JTextArea();

        setTitle("Calcus");
        setName("Calculs"); // NOI18N
        setPreferredSize(new java.awt.Dimension(825, 650));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(circuitJTextPanel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 780, 250));

        pulsationLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pulsationLabel.setText("Pulsation");
        getContentPane().add(pulsationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 110, 30));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setText("100");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 110, 30));

        recalculeButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        recalculeButton.setText("Recalcule");
        recalculeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recalculeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(recalculeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 120, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 780, 10));

        calculTextArea.setColumns(20);
        calculTextArea.setRows(5);
        calculTextArea.setText("Courant et Tension des composants: ");
        jScrollPane3.setViewportView(calculTextArea);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 770, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void recalculeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recalculeButtonActionPerformed
        // TODO add your handling code here:
        calculTextArea.setText("Courant et Tension des composants:");
        double pulsation = Double.parseDouble(jTextField1.getText());
        MatriceRectangulaire mrec = null;
        try {
            mrec = c.calculs(pulsation);
            Complex[] mat = mrec.getSol();
            int n = c.getCompoCircuit().size();
            for (Composant cur : c.getCompoCircuit()) {
                int id = cur.getId() - 1;
                Complex v = mat[id];
                Complex i = mat[id + n];
                String out = cur.toString();
                out += ": V =[ComPol " + v.module() + "ei(" + v.argument() + ")]; I = [ComPol";
                out += i.module() + " ei(" + i.argument() + ")]\n";
                calculTextArea.append(out);
            }
        } catch (Exception ex) {
            calculTextArea.setText("Vérifier la validité du Circuit !!!");
            
        }

    }//GEN-LAST:event_recalculeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculsInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculsInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculsInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculsInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculsInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea calculTextArea;
    private javax.swing.JTextPane circuitJTextPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel pulsationLabel;
    private javax.swing.JButton recalculeButton;
    // End of variables declaration//GEN-END:variables
}
