/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sth_s2;

import java.awt.Graphics2D;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Line2D;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.JTextArea;

/**
 *
 * @author Nezz
 */
public class NoeudInterface extends javax.swing.JFrame {

    /**
     * Creates new form NoeudInterface
     */
    private Ellipse2D circbuffer;
    private Circuit cir;
    private javax.swing.JTextArea logTextArea;
    private JPanel mainPanel;
    private BufferedImage image;
    private Graphics2D g;
    private List<Line2D> lineContainer = new ArrayList();
    private List<Ellipse2D> circContainer = new ArrayList();
    private List<MyImage> imgContainer = new ArrayList();

    public NoeudInterface() {
        initComponents();
    }

    public NoeudInterface(Circuit cir, JTextArea logTextArea, JPanel mainPanel, List<Line2D> lineContainer, List<Ellipse2D> circContainer, List<MyImage> imgContainer) {
        initComponents();
        this.cir = cir;
        //pont  passage par référence losrque on fait des changement sur ce log text
        //Celui du applicationInterface change
        this.logTextArea = logTextArea;
        //de meme
        this.mainPanel = mainPanel;
        this.lineContainer = lineContainer;
        this.circContainer = circContainer;
        this.imgContainer = imgContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitreLabel = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        pxLabel = new javax.swing.JLabel();
        pyLabel = new javax.swing.JLabel();
        pyTextField = new javax.swing.JTextField();
        pxTextField = new javax.swing.JTextField();
        creeButton = new javax.swing.JButton();

        setTitle("Nouveau Noeud");
        setPreferredSize(new java.awt.Dimension(420, 320));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitreLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TitreLabel.setText("Création d'un nouveau Noeud");
        getContentPane().add(TitreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 240, 40));

        errorLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(errorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 110, 30));

        pxLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pxLabel.setText("Px :");
        getContentPane().add(pxLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 40, 40));

        pyLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pyLabel.setText("Py :");
        getContentPane().add(pyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 40, 40));
        getContentPane().add(pyTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 80, 30));
        getContentPane().add(pxTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 80, 30));

        creeButton.setText("Créer");
        creeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(creeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 183, 80, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creeButtonActionPerformed
        // TODO add your handling code here:
        double px = 0, py = 0;
        boolean cond = false;
        try {
            px = Double.parseDouble(pxTextField.getText());
            py = Double.parseDouble(pyTextField.getText());
        } catch (Exception e) {
            cond = true;
            System.out.println("Invalid Output");
            errorLabel.setText("invalid Output");
        }
        int id = cir.getNoeudCircuit().size() + 1;
        if (!cond) {
            logTextArea.append("Creating node : " + id + "( " + px + " , " + py + " )\n");
            System.out.println("Creating node : " + id + "( " + px + " , " + py + " )");
            errorLabel.setText("");
            cir.ajouterNoeudCircuit(new Noeud(id, px, py));
            if (g == null) {
                g = (Graphics2D) mainPanel.getGraphics();
            }
            mainPanel.update(g);
            circbuffer = new Ellipse2D.Float((float) px, (float) py, (float) 20, (float) 20);
            circContainer.add(circbuffer);
            DrawAll();
        }
    }//GEN-LAST:event_creeButtonActionPerformed
    private void DrawAll() {
        for (int x = 0; x < lineContainer.size(); x++) {
            g.draw(lineContainer.get(x));
        }
        for (int x = 0; x < circContainer.size(); x++) {
            g.draw(circContainer.get(x));
        }
        for (int x = 0; x < imgContainer.size(); x++) {
            MyImage img = imgContainer.get(x);
            g.drawImage(img.getImg(), img.getX(), img.getY(), this);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NoeudInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NoeudInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NoeudInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NoeudInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NoeudInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TitreLabel;
    private javax.swing.JButton creeButton;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel pxLabel;
    private javax.swing.JTextField pxTextField;
    private javax.swing.JLabel pyLabel;
    private javax.swing.JTextField pyTextField;
    // End of variables declaration//GEN-END:variables
}
